
import java.awt.Dimension;
import java.util.Arrays;
import java.util.List;
import javax.swing.JList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class DropdownPanel extends javax.swing.JPanel {
    private String[] items;
    private String currentValue;
    private Runnable selectionCallback;
    
    /**
     * Creates new form DropdownPanel
     */
    public DropdownPanel(String[] items) {
        this.items = items;
        setPreferredSize(new Dimension(1000, 1000));
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("jLabel1");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents

    public void setSelectionCallback(Runnable callback) {
        this.selectionCallback = callback;
    }
    
//    public int getPreferredHeight() {
//        return list.getPreferredSize().height + 10;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
