/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lcbusana.auth;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Frame;
import javax.swing.JFrame;
import lcbusana.Layout;

/**
 *
 * @author Acer
 */
public class FormAuth extends javax.swing.JFrame {
    private CardLayout cardAuth;
    private CardLayout cardHello;
    
    /**
     * Creates new form FormAuth
     */
    public FormAuth() {
        initComponents();
        this.cardAuth = (CardLayout) authPanel.getLayout();
        this.cardHello = (CardLayout) helloPanel.getLayout();
        
        setExtendedState(6);
        komponenAuth();
    }

    public FormAuth(String sesiAuth){
        this();
        ubahPanel(sesiAuth);
    }
    
    private void komponenAuth(){    
        //Auth Panel
        authPanel.add(new Login(this), "Login");
        authPanel.add(new Register(this), "Register");
        
        //Hello Panel
        helloPanel.add(new HelloLogin(this), "Login");
        helloPanel.add(new HelloRegister(this), "Register");
    }
    
    public void ubahPanel(String sesiAuth){
        switch(sesiAuth){
            case "Register" -> {
                cardAuth.show(authPanel, sesiAuth);
                
                if ((getExtendedState() & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH) {
                    cardHello.show(helloPanel, sesiAuth);
                    ubahUrutanPanel(helloPanel, authPanel);
                }
            }
            
            case "Login" -> {
                cardAuth.show(authPanel, sesiAuth);
                if ((getExtendedState() & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH) {
                    cardHello.show(helloPanel, sesiAuth);
                    ubahUrutanPanel(authPanel, helloPanel);
                }
            }
        }
    }
    
    private void ubahUrutanPanel(Component... urutanBaru) {
        Container contentPane = getContentPane();
        contentPane.removeAll();

        for (Component komponen : urutanBaru) {
            contentPane.add(komponen); // Tambahkan sesuai urutan baru
        }

        contentPane.revalidate(); // Perbarui layout
        contentPane.repaint();    // Gambar ulang
    }
    
    public void kembaliKeHalamanUtama(){
        dispose();
        new Layout().setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authPanel = new javax.swing.JPanel();
        helloPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(600, 700));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        authPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(authPanel);

        helloPanel.setBackground(new java.awt.Color(207, 183, 146));
        helloPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(helloPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        int oldState = evt.getOldState();
        int newState = evt.getNewState();
        Container contentPane = getContentPane();
                
        // Cek jika JFrame pertama kali dimulai dengan ukuran maximize
        if (getExtendedState() == JFrame.MAXIMIZED_BOTH) {
            contentPane.add(helloPanel);
        }
    
        if ((oldState & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH &&
            (newState & Frame.MAXIMIZED_BOTH) != Frame.MAXIMIZED_BOTH) {
            // Hapus hello panel
            contentPane.remove(helloPanel);
        } else if ((oldState & Frame.MAXIMIZED_BOTH) != Frame.MAXIMIZED_BOTH &&
                   (newState & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH) {
            //Kembalikan lagi hello panel
            contentPane.add(helloPanel);
        }
        
        // Reload Tampilan
        contentPane.revalidate();
        contentPane.repaint();
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Container contentPane = getContentPane();
    
        if ((getExtendedState() & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH) {
            contentPane.add(helloPanel);
        } else {
            contentPane.remove(helloPanel);
        }

        contentPane.revalidate();
        contentPane.repaint();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAuth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authPanel;
    private javax.swing.JPanel helloPanel;
    // End of variables declaration//GEN-END:variables
}
