/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lcbusana.auth;

import decorationcomponent.BackgroundPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Frame;
import javax.swing.JFrame;
import lcbusana.Layout;
import session.Auth;

/**
 *
 * @author Acer
 */
public class FormAuth extends javax.swing.JFrame {
    private CardLayout cardAuth;
    private Layout main;
    
    //final properties
    private final Login login = new Login(this);
    private final Register register = new Register(this);
    
    /**
     * Creates new form FormAuth
     */
    public FormAuth() {
        initComponents();
        this.cardAuth = (CardLayout) authPanel.getLayout();
        
        setExtendedState(6);
        komponenAuth();
        
    }
    
    /**
     * @return the main
     */
    public Layout getMain() {
        return main;
    }

    /**
     * @param main the main to set
     */
    public void setMain(Layout main) {
        this.main = main;
    }
    
    private void komponenAuth(){    
        //Auth Panel
        authPanel.add(login, "Login");
        authPanel.add(register, "Register");
    }
    
    public void ubahPanel(String sesiAuth){
        switch(sesiAuth){
            case "Register" -> {
                cardAuth.show(authPanel, sesiAuth);
                
                if ((getExtendedState() & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH) {
                    ubahUrutanPanel(welcomePanel, authPanel);
                }
            }
            
            case "Login" -> {
                cardAuth.show(authPanel, sesiAuth);
                
                if ((getExtendedState() & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH) {
                    ubahUrutanPanel(authPanel, welcomePanel);
                }
            }
        }
    }
    
    private void ubahUrutanPanel(Component... urutanBaru) {
        Container contentPane = getContentPane();
        contentPane.removeAll();

        for (Component komponen : urutanBaru) {
            contentPane.add(komponen); // Tambahkan sesuai urutan baru
        }

        contentPane.revalidate(); // Perbarui layout
        contentPane.repaint();    // Gambar ulang
    }
    
    public void kembaliKeHalamanUtama(){
        setVisible(false);
        getMain().setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        authPanel = new javax.swing.JPanel();
        welcomePanel = new BackgroundPanel("lcbusana-welcome.png");
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LC Busana");
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(600, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        authPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(authPanel);

        welcomePanel.setLayout(new java.awt.GridBagLayout());

        btnBack.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(207, 183, 146));
        btnBack.setText("kembali");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        welcomePanel.add(btnBack, gridBagConstraints);

        getContentPane().add(welcomePanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        int oldState = evt.getOldState();
        int newState = evt.getNewState();
        Container contentPane = getContentPane();
                
        // Cek jika JFrame pertama kali dimulai dengan ukuran maximize
        if (getExtendedState() == JFrame.MAXIMIZED_BOTH) {
            contentPane.add(welcomePanel);
        }
    
        if ((oldState & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH &&
            (newState & Frame.MAXIMIZED_BOTH) != Frame.MAXIMIZED_BOTH) {
            // Hapus welcome panel
            contentPane.remove(welcomePanel);
        } else if ((oldState & Frame.MAXIMIZED_BOTH) != Frame.MAXIMIZED_BOTH &&
                   (newState & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH) {
            //Kembalikan lagi hello panel
            contentPane.add(welcomePanel);
        }
        
        // Reload Tampilan
        contentPane.revalidate();
        contentPane.repaint();
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Container contentPane = getContentPane();
    
        if ((getExtendedState() & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH) {
            contentPane.add(welcomePanel);
        } else {
            contentPane.remove(welcomePanel);
        }

        contentPane.revalidate();
        contentPane.repaint();
    }//GEN-LAST:event_formWindowOpened

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        kembaliKeHalamanUtama();
    }//GEN-LAST:event_btnBackActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //Membersihkan sesi autentikasi
        Auth.getInstance().clear();
        
        //Mengosongkan field
        login.setDefaultField();
        register.setDefaultField();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAuth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
