/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lcbusana;

import decorationcomponent.RoundedButton;
import decorationcomponent.RoundedLabel;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import session.Auth;
import tools.ImageUtil;

/**
 *
 * @author Acer
 */
public class FormProfil extends javax.swing.JPanel {
    private Layout main;
    /**
     * Creates new form FormProfil
     */
    public FormProfil(JFrame frame) {
        initComponents();
        this.main = (Layout) frame;
        
        setPhotoProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlProfil = new javax.swing.JPanel();
        lbPhoto = new RoundedLabel(20);
        btnEditPhoto = new RoundedButton(10);
        lbUsername = new javax.swing.JLabel();
        tztUsername = new javax.swing.JTextField();
        btnUbahPassword = new RoundedButton(10);
        jLabel5 = new RoundedLabel(20);
        pnlDataDiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new RoundedButton(10);
        jTextField4 = new javax.swing.JTextField();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.GridLayout());

        pnlProfil.setOpaque(false);
        pnlProfil.setLayout(new java.awt.GridBagLayout());

        lbPhoto.setBackground(new java.awt.Color(255, 255, 255));
        lbPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/default-profile.png"))); // NOI18N
        lbPhoto.setPreferredSize(new java.awt.Dimension(250, 250));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        pnlProfil.add(lbPhoto, gridBagConstraints);

        btnEditPhoto.setBackground(new java.awt.Color(207, 183, 146));
        btnEditPhoto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditPhoto.setText("Edit Photo Profile");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlProfil.add(btnEditPhoto, gridBagConstraints);

        lbUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbUsername.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlProfil.add(lbUsername, gridBagConstraints);

        tztUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        pnlProfil.add(tztUsername, gridBagConstraints);

        btnUbahPassword.setBackground(new java.awt.Color(101, 84, 51));
        btnUbahPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUbahPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahPassword.setText("Ubah Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        pnlProfil.add(btnUbahPassword, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(207, 183, 146));
        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pengaturan Profil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlProfil.add(jLabel5, gridBagConstraints);

        add(pnlProfil);

        pnlDataDiri.setOpaque(false);
        pnlDataDiri.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        pnlDataDiri.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("No WhatsApp");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        pnlDataDiri.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        pnlDataDiri.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Alamat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        pnlDataDiri.add(jLabel4, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        pnlDataDiri.add(jTextField1, gridBagConstraints);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        pnlDataDiri.add(jTextField2, gridBagConstraints);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        pnlDataDiri.add(jTextField3, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(207, 183, 146));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Simpan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        pnlDataDiri.add(jButton1, gridBagConstraints);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        pnlDataDiri.add(jTextField4, gridBagConstraints);

        add(pnlDataDiri);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/bg-profile.png"));
        Image img = icon.getImage();
        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
    }
    
    private void setPhotoProfile(){
        String pathPhoto = "attachments/Profil/" + Auth.getInstance().getAuthUser();
        URL urlDefault = getClass().getResource("/image/default-profile.png");
                
        ImageUtil.setImageToLabel(lbPhoto, pathPhoto, urlDefault);
    }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditPhoto;
    private javax.swing.JButton btnUbahPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbPhoto;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel pnlDataDiri;
    private javax.swing.JPanel pnlProfil;
    private javax.swing.JTextField tztUsername;
    // End of variables declaration//GEN-END:variables
}
