/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lcbusana;
import database.DataPesanBusana;
import decorationcomponent.RoundedButton;
import decorationcomponent.RoundedPanel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author apitf
 */
public class FormPesanBusana_Ukuran extends javax.swing.JPanel {
    private Layout main;
    /**
     * Creates new form FormPesanBusana_Ukuran
     */
    public FormPesanBusana_Ukuran(JFrame frame) {
        initComponents();
        this.main = (Layout) frame;
        
        alignTextJSpinnerLeft();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlForm = new RoundedPanel(50);
        lblLingkarDada = new javax.swing.JLabel();
        lblTinggiBadan = new javax.swing.JLabel();
        lblLebarBahu = new javax.swing.JLabel();
        lblLingkarPinggang = new javax.swing.JLabel();
        lblLingkarPinggul = new javax.swing.JLabel();
        lblPanjangLengan = new javax.swing.JLabel();
        lblPanjangBaju = new javax.swing.JLabel();
        jsLingkarDada = new javax.swing.JSpinner();
        jsTinggiBadan = new javax.swing.JSpinner();
        jsLebarBahu = new javax.swing.JSpinner();
        jsLingkarPinggang = new javax.swing.JSpinner();
        jsLingkarPinggul = new javax.swing.JSpinner();
        jsPanjangLengan = new javax.swing.JSpinner();
        jsPanjangBaju = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        btnNext = new RoundedButton(10);
        btnSebelum = new RoundedButton(10);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        jLabel1.setText("Pesan Busana (Tabel Pengukuran)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jPanel1, gridBagConstraints);

        pnlForm.setBackground(new java.awt.Color(207, 183, 146));
        pnlForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        pnlForm.setLayout(new java.awt.GridBagLayout());

        lblLingkarDada.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLingkarDada.setText("Lingkar dada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblLingkarDada, gridBagConstraints);

        lblTinggiBadan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTinggiBadan.setText("Tinggi Badan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblTinggiBadan, gridBagConstraints);

        lblLebarBahu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLebarBahu.setText("Lebar Bahu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblLebarBahu, gridBagConstraints);

        lblLingkarPinggang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLingkarPinggang.setText("Lingkar Pinggang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblLingkarPinggang, gridBagConstraints);

        lblLingkarPinggul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLingkarPinggul.setText("Lingkar Pinggul");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblLingkarPinggul, gridBagConstraints);

        lblPanjangLengan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPanjangLengan.setText("Panjang Lengan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblPanjangLengan, gridBagConstraints);

        lblPanjangBaju.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPanjangBaju.setText("Panjang Baju");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblPanjangBaju, gridBagConstraints);

        jsLingkarDada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jsLingkarDada.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jsLingkarDada, gridBagConstraints);

        jsTinggiBadan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jsTinggiBadan.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jsTinggiBadan, gridBagConstraints);

        jsLebarBahu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jsLebarBahu.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jsLebarBahu, gridBagConstraints);

        jsLingkarPinggang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jsLingkarPinggang.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jsLingkarPinggang, gridBagConstraints);

        jsLingkarPinggul.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jsLingkarPinggul.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jsLingkarPinggul, gridBagConstraints);

        jsPanjangLengan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jsPanjangLengan.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jsPanjangLengan, gridBagConstraints);

        jsPanjangBaju.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jsPanjangBaju.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jsPanjangBaju, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        add(pnlForm, gridBagConstraints);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnNext.setBackground(new java.awt.Color(207, 183, 146));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNext.setText("Berikutnya >");
        btnNext.setBorderPainted(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 80);
        jPanel3.add(btnNext, gridBagConstraints);

        btnSebelum.setBackground(new java.awt.Color(207, 183, 146));
        btnSebelum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSebelum.setText("<Sebelumnya");
        btnSebelum.setBorderPainted(false);
        btnSebelum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSebelumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(btnSebelum, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/bg-form.png"));
        Image img = icon.getImage();
        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
    }
    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // Ambil nilai dari JSpinner
        int lingkarDada = (int) jsLingkarDada.getValue();
        int lingkarPinggang = (int) jsLingkarPinggang.getValue();
        int lingkarPinggul = (int) jsLingkarPinggul.getValue();
        int panjangLengan = (int) jsPanjangLengan.getValue();
        int panjangBaju = (int) jsPanjangBaju.getValue();
        int tinggiBadan = (int) jsTinggiBadan.getValue();
        int lebarBahu = (int) jsLebarBahu.getValue();

        // Validasi: Semua field harus diisi (> 0)
        if (lingkarDada <= 0 ||
                lingkarPinggang <= 0 ||
                lingkarPinggul <= 0 || 
                panjangLengan <= 0 || 
                panjangBaju <= 0 || 
                tinggiBadan <= 0 || 
                lebarBahu <= 0) {
            JOptionPane.showMessageDialog(this, "Semua input harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            //Simpan Data
            DataPesanBusana data= DataPesanBusana.getInstance();
            data.setLingkarDada(lingkarDada);
            data.setLingkarPinggang(lingkarPinggang);
            data.setLingkarPinggul(lingkarPinggul);
            data.setPanjangLengan(panjangLengan);
            data.setPanjangBaju(panjangBaju);
            data.setTinggiBadan(tinggiBadan);
            data.setLebarBahu(lebarBahu);
            
            // Pindah ke halaman berikutnya
            main.ubahPanel("btambahan");
        }    
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSebelumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSebelumActionPerformed
        main.ubahPanel("bmain");
    }//GEN-LAST:event_btnSebelumActionPerformed

    private void alignTextJSpinnerLeft(){
        // Array atau daftar semua JSpinner yang ingin diubah
        JSpinner[] spinners = {jsLingkarDada, jsTinggiBadan, jsLingkarPinggang, jsLingkarPinggul, jsPanjangLengan, jsPanjangBaju,jsLebarBahu }; // Sesuaikan dengan nama spinner Anda

        for (JSpinner spinner : spinners) {
            JComponent editor = spinner.getEditor();
            if (editor instanceof JSpinner.DefaultEditor) {
                JSpinner.DefaultEditor defaultEditor = (JSpinner.DefaultEditor) editor;
                JTextField textField = defaultEditor.getTextField();
                textField.setHorizontalAlignment(SwingConstants.LEFT);
            }
        }
    }
    
    public void clear(){
        jsLingkarDada.setValue(0);
        jsTinggiBadan.setValue(0);
        jsLingkarPinggang.setValue(0);
        jsLingkarPinggul.setValue(0);
        jsPanjangLengan.setValue(0);
        jsPanjangBaju.setValue(0);
        jsLebarBahu.setValue(0);       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSebelum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jsLebarBahu;
    private javax.swing.JSpinner jsLingkarDada;
    private javax.swing.JSpinner jsLingkarPinggang;
    private javax.swing.JSpinner jsLingkarPinggul;
    private javax.swing.JSpinner jsPanjangBaju;
    private javax.swing.JSpinner jsPanjangLengan;
    private javax.swing.JSpinner jsTinggiBadan;
    private javax.swing.JLabel lblLebarBahu;
    private javax.swing.JLabel lblLingkarDada;
    private javax.swing.JLabel lblLingkarPinggang;
    private javax.swing.JLabel lblLingkarPinggul;
    private javax.swing.JLabel lblPanjangBaju;
    private javax.swing.JLabel lblPanjangLengan;
    private javax.swing.JLabel lblTinggiBadan;
    private javax.swing.JPanel pnlForm;
    // End of variables declaration//GEN-END:variables
}
