
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lcbusana;

import database.DataPermakBusana;
import database.DataPesanBusana;
import decorationcomponent.RoundedButton;
import decorationcomponent.RoundedPanel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import java.sql.SQLException;

/**
 *
 * @author Acer
 */
public class FormDataDiri extends javax.swing.JPanel {
    private Layout main;
    
    /**
     * Creates new form DataDiri
     */
    public FormDataDiri(JFrame frame) {
        initComponents();
        this.main = (Layout) frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlForm = new RoundedPanel(50);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNoWA = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnSelesai = new RoundedButton(10);
        btnSebelumnya = new RoundedButton(10);

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        jLabel1.setText("Data Diri");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jPanel1, gridBagConstraints);

        pnlForm.setBackground(new java.awt.Color(207, 183, 146));
        pnlForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        pnlForm.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nomor WA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Alamat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jLabel5, gridBagConstraints);

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(txtNama, gridBagConstraints);

        txtNoWA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNoWA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoWAKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(txtNoWA, gridBagConstraints);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(txtEmail, gridBagConstraints);

        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAlamat.setRows(5);
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlamatKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtAlamat);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        add(pnlForm, gridBagConstraints);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnSelesai.setBackground(new java.awt.Color(207, 183, 146));
        btnSelesai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSelesai.setText("Selesai");
        btnSelesai.setBorderPainted(false);
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 80);
        jPanel2.add(btnSelesai, gridBagConstraints);

        btnSebelumnya.setBackground(new java.awt.Color(207, 183, 146));
        btnSebelumnya.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSebelumnya.setText("Batal");
        btnSebelumnya.setBorderPainted(false);
        btnSebelumnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSebelumnyaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel2.add(btnSebelumnya, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/bg-form.png"));
        Image img = icon.getImage();
        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
    }

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // Ambil nilai dari setiap input field
        String nama = txtNama.getText().trim();
        String noWa = txtNoWA.getText().trim();
        String email = txtEmail.getText().trim();
        String alamat = txtAlamat.getText().trim();

        // Validasi apakah ada yang kosong
        if (nama.isEmpty() || noWa.isEmpty() || email.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua input harus diisi sebelum melanjutkan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Cek Apakah sedang mengedit
        if(main.isOnEdit()){
            switch(main.getStatus()){
                case "Busana" -> updateDataPesanBusana(nama, noWa, email, alamat);            
                case "Permak" -> updateDataPermakBusana(nama, noWa, email, alamat);
            }          
            
            // Selesai Edit, kembali kembali ke Pesanan
             main.ubahPanel("pesanan");
        } else {
            switch(main.getStatus()){
                case "Busana" -> tambahDataPesanBusana(nama, noWa, email, alamat);            
                case "Permak" -> tambahDataPermakBusana(nama, noWa, email, alamat);
            } 
            
            // Selesai, kembali ke form dashboatd
            main.ubahPanel("dashboard"); 
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnSebelumnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSebelumnyaActionPerformed
        //kembali ke form dashboatd
        main.ubahPanel("dashboard");
    }//GEN-LAST:event_btnSebelumnyaActionPerformed

    private boolean tambahDataPesanBusana(String nama, String no, String email, String alamat) {        
        try {
            DataPesanBusana data= DataPesanBusana.getInstance();
            data.setNamaLengkap(nama);
            data.setNomorTelepon(no);
            data.setAlamatEmail(email);
            data.setAlamatPengiriman(alamat);
            data.save();
            
            return true;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data \n" + e, "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private void tambahDataPermakBusana(String nama, String no, String email, String alamat) {        
        DataPermakBusana data = DataPermakBusana.getInstance();
        data.setNamaLengkap(nama);
        data.setNomorTelepon(no);
        data.setAlamatEmail(email);
        data.setAlamatPengiriman(alamat);
        data.save();
    }
    
    private boolean updateDataPesanBusana(String nama, String no, String email, String alamat) {
        try {
            DataPesanBusana data= DataPesanBusana.getInstance();
            data.setNamaLengkap(nama);
            data.setNomorTelepon(no);
            data.setAlamatEmail(email);
            data.setAlamatPengiriman(alamat);
            data.update();
            
            return true;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Memperbarui Data \n" + e, "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private void updateDataPermakBusana(String nama, String no, String email, String alamat) {
        DataPermakBusana data= DataPermakBusana.getInstance();
        data.setNamaLengkap(nama);
        data.setNomorTelepon(no);
        data.setAlamatEmail(email);
        data.setAlamatPengiriman(alamat);
        data.update();
    }
    
    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        char c = evt.getKeyChar();
    
        // Jika tombol yang ditekan adalah Backspace, biarkan tanpa validasi
        if (c == KeyEvent.VK_BACK_SPACE) {
            return;
        }

        // Hanya menerima huruf (A-Z, a-z) dan spasi
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume(); // Mencegah karakter tidak valid masuk
            JOptionPane.showMessageDialog(this, "Hanya huruf dan spasi yang diperbolehkan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtNamaKeyTyped

    private void txtNoWAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoWAKeyTyped
       char c = evt.getKeyChar();
    
        // Jika tombol yang ditekan adalah Backspace, biarkan tanpa validasi
        if (c == KeyEvent.VK_BACK_SPACE) {
            return;
        }

        // Hanya menerima huruf (A-Z, a-z) dan spasi
        if (!Character.isDigit(c)) {
            evt.consume(); // Mencegah karakter tidak valid masuk
            JOptionPane.showMessageDialog(this, "Teks hanya berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtNoWAKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        char c = evt.getKeyChar();
    
        // Jika tombol yang ditekan adalah Backspace, biarkan tanpa validasi
        if (c == KeyEvent.VK_BACK_SPACE) {
            return;
        }

        // Hanya menerima huruf (A-Z, a-z), spasi, titik, dan @
        if (!Character.isLetter(c) && c != ' ' && c != '.' && c != '@') {
            evt.consume(); // Mencegah karakter tidak valid masuk
            JOptionPane.showMessageDialog(this, "Hanya huruf, spasi, titik, dan @ yang diperbolehkan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtAlamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyTyped
        char c = evt.getKeyChar();
    
        // Jika tombol yang ditekan adalah Backspace, biarkan tanpa validasi
        if (c == KeyEvent.VK_BACK_SPACE) {
            return;
        }

        // Hanya menerima huruf (A-Z, a-z) dan spasi
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume(); // Mencegah karakter tidak valid masuk
            JOptionPane.showMessageDialog(this, "Hanya huruf dan spasi yang diperbolehkan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtAlamatKeyTyped

    public void clear(){
        txtAlamat.setText(null);
        txtEmail.setText(null);
        txtNama.setText(null);
        txtNoWA.setText(null);
    }
    
    public void isiDataEditPesanBusana(){
        DataPesanBusana data = DataPesanBusana.getInstance();
        txtAlamat.setText(data.getAlamatPengiriman());
        txtEmail.setText(data.getAlamatEmail());
        txtNama.setText(data.getNamaLengkap());
        txtNoWA.setText(data.getNomorTelepon());
    }
    
    void isiDataEditPermakBusana() {
        DataPermakBusana data = DataPermakBusana.getInstance();
        txtAlamat.setText(data.getAlamatPengiriman());
        txtEmail.setText(data.getAlamatEmail());
        txtNama.setText(data.getNamaLengkap());
        txtNoWA.setText(data.getNomorTelepon());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSebelumnya;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoWA;
    // End of variables declaration//GEN-END:variables
}
