/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lcbusana;
import database.DataPesanBusana;
import decorationcomponent.RoundedButton;
import decorationcomponent.RoundedPanel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author apitf
 */
public class FormPesanBusana_Tambahan extends javax.swing.JPanel {
    private Layout main;
    
    /**
     * Creates new form FormPesanBusana_Tambahan
     */
    public FormPesanBusana_Tambahan(JFrame frame) {
        initComponents();
        this.main = (Layout) frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlForm = new RoundedPanel(50);
        lblApk = new javax.swing.JLabel();
        lblDetail = new javax.swing.JLabel();
        lblKebutuhan = new javax.swing.JLabel();
        txtApk = new javax.swing.JTextField();
        txtDetail = new javax.swing.JTextField();
        txtKebutuhan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnNext = new RoundedButton(10);
        btnSebelum = new RoundedButton(10);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        jLabel1.setText("Pesan Busana (Detail Tambahan)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jPanel1, gridBagConstraints);

        pnlForm.setBackground(new java.awt.Color(207, 183, 146));
        pnlForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        pnlForm.setLayout(new java.awt.GridBagLayout());

        lblApk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblApk.setText("Aplikasi Tambahan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblApk, gridBagConstraints);

        lblDetail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDetail.setText("Detail Khusus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblDetail, gridBagConstraints);

        lblKebutuhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKebutuhan.setText("Kebutuhan Khusus ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblKebutuhan, gridBagConstraints);

        txtApk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(txtApk, gridBagConstraints);

        txtDetail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(txtDetail, gridBagConstraints);

        txtKebutuhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(txtKebutuhan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        add(pnlForm, gridBagConstraints);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnNext.setBackground(new java.awt.Color(207, 183, 146));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNext.setText("Berikutnya >");
        btnNext.setBorderPainted(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 80);
        jPanel3.add(btnNext, gridBagConstraints);

        btnSebelum.setBackground(new java.awt.Color(207, 183, 146));
        btnSebelum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSebelum.setText("<Sebelumnya");
        btnSebelum.setBorderPainted(false);
        btnSebelum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSebelumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(btnSebelum, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/bg-form.png"));
        Image img = icon.getImage();
        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
    }
    
    private void btnSebelumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSebelumActionPerformed
        // Pindah ke halaman Sebelumnya Form Busana (Ukuran)
        main.ubahPanel("bukuran");
    }//GEN-LAST:event_btnSebelumActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // Ambil teks dari setiap TextField
        String aplikasiTambahan = txtApk.getText().trim();
        String detailKhusus = txtDetail.getText().trim();
        String kebutuhanKhusus = txtKebutuhan.getText().trim();

        // Periksa apakah ada field yang kosong
        if (aplikasiTambahan.isEmpty() || detailKhusus.isEmpty() || kebutuhanKhusus.isEmpty()) {
            int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin untuk tidak memberi detail tambahan?", 
                "Konfirmasi", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);

            // Jika user memilih "No", hentikan proses
            if (konfirmasi == JOptionPane.NO_OPTION) {
                return;
            }
            
            if (konfirmasi == JOptionPane.YES_OPTION) {
                //Simpan data
                DataPesanBusana data= DataPesanBusana.getInstance();
                data.setAplikasiTambahan(aplikasiTambahan);
                data.setDetailKhusus(detailKhusus);
                data.setKebutuhanKhusus(kebutuhanKhusus);
        
                //Menghitung biaya berdasarkan field yang dipilih
//                hitungBiaya();
                
                // Lanjut ke halaman berikutnya dengan mengubah panel
                main.ubahPanel("bwaktubiaya");
            }
        } else {
            //Simpan data
            DataPesanBusana data= DataPesanBusana.getInstance();
            data.setAplikasiTambahan(aplikasiTambahan);
            data.setDetailKhusus(detailKhusus);
            data.setKebutuhanKhusus(kebutuhanKhusus);

            //Menghitung biaya berdasarkan field yang dipilih
//            hitungBiaya();
                
            // Lanjut ke halaman berikutnya dengan mengubah panel
            main.ubahPanel("bwaktubiaya");
        }    
    }//GEN-LAST:event_btnNextActionPerformed

    public void clear(){
        txtApk.setText(null);
        txtDetail.setText(null);
        txtKebutuhan.setText(null);
    }
    
    private void hitungBiaya(){
        DataPesanBusana data = DataPesanBusana.getInstance();
        
        // Menghitung harga berdasarkan detail tambahan
        String[] daftarTambahan = {data.getAplikasiTambahan(), data.getDetailKhusus(), data.getKebutuhanKhusus()};
        
        for(String tambahan : daftarTambahan){
            if(!tambahan.isEmpty()){
                data.setKisaranBudget(data.getKisaranBudget() + 50000);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSebelum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblApk;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblKebutuhan;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JTextField txtApk;
    private javax.swing.JTextField txtDetail;
    private javax.swing.JTextField txtKebutuhan;
    // End of variables declaration//GEN-END:variables
}
