package lcbusana;

import database.DataPermakBusana;
import decorationcomponent.RoundedButton;
import decorationcomponent.RoundedPanel;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Raden Ayu HIkmah R
 */
public class FormPermak_Main extends javax.swing.JPanel {
    private Layout main;
    
    /**
     * Creates new form PermakBusana
     */
    public FormPermak_Main(JFrame frame) {
        initComponents();
        this.main = (Layout) frame;
        
        alignTextJSpinnerLeft();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/bg-form.png"));
        Image img = icon.getImage();
        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlForm = new RoundedPanel(50);
        lblJenisBusanaPermak = new javax.swing.JLabel();
        lblBahanPermak = new javax.swing.JLabel();
        lblJmlPermak = new javax.swing.JLabel();
        cbJenisBusanaPermak = new javax.swing.JComboBox<>();
        spJmlPermak = new javax.swing.JSpinner();
        txtBahanPermak = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnLanjut = new RoundedButton(10);
        btnBatalPermak = new RoundedButton(10);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        jLabel1.setText("Permak Busana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jPanel1, gridBagConstraints);

        pnlForm.setBackground(new java.awt.Color(207, 183, 146));
        pnlForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        pnlForm.setLayout(new java.awt.GridBagLayout());

        lblJenisBusanaPermak.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJenisBusanaPermak.setText("Jenis Pakaian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblJenisBusanaPermak, gridBagConstraints);

        lblBahanPermak.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBahanPermak.setText("Bahan Pakaian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblBahanPermak, gridBagConstraints);

        lblJmlPermak.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJmlPermak.setText("Jumlah Pakaian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblJmlPermak, gridBagConstraints);

        cbJenisBusanaPermak.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbJenisBusanaPermak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kemeja", "Celana", "Gaun", "Jaket", "Kebaya", "Daster" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(cbJenisBusanaPermak, gridBagConstraints);

        spJmlPermak.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(spJmlPermak, gridBagConstraints);

        txtBahanPermak.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBahanPermak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBahanPermakKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(txtBahanPermak, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        add(pnlForm, gridBagConstraints);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnLanjut.setBackground(new java.awt.Color(207, 183, 146));
        btnLanjut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLanjut.setText("Berikutnya>");
        btnLanjut.setBorderPainted(false);
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 80);
        jPanel3.add(btnLanjut, gridBagConstraints);

        btnBatalPermak.setBackground(new java.awt.Color(207, 183, 146));
        btnBatalPermak.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatalPermak.setText("Batal");
        btnBatalPermak.setBorderPainted(false);
        btnBatalPermak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPermakActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(btnBatalPermak, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        // Ambil nilai dari setiap input field
        String jenis = (String) cbJenisBusanaPermak.getSelectedItem().toString().trim();
        String bahan = txtBahanPermak.getText().trim();
        int jmlPermak = (int) spJmlPermak.getValue();
        
        // Validasi apakah ada yang kosong
        if (bahan.isEmpty() || jmlPermak <= 0 ) {
            JOptionPane.showMessageDialog(this, "Semua input harus diisi sebelum melanjutkan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Simpan data
        DataPermakBusana data = DataPermakBusana.getInstance();
        data.setJenisPakaian(jenis);
        data.setBahanPakaian(bahan);
        data.setJumlahPakaian(jmlPermak);
        
        // Pindah ke halaman selanjutnya Form Permak (jenis)
        main.ubahPanel("pjenis");   
    }//GEN-LAST:event_btnLanjutActionPerformed

    private void btnBatalPermakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPermakActionPerformed
        // Kembali ke dashboard
        main.ubahPanel("dashboard");
    }//GEN-LAST:event_btnBatalPermakActionPerformed

    private void txtBahanPermakKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBahanPermakKeyTyped
        char c = evt.getKeyChar();
    
        // Jika tombol yang ditekan adalah Backspace, biarkan tanpa validasi
        if (c == KeyEvent.VK_BACK_SPACE) {
            return;
        }

        // Hanya menerima huruf (A-Z, a-z) dan spasi
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume(); // Mencegah karakter tidak valid masuk
            JOptionPane.showMessageDialog(this, "Hanya huruf dan spasi yang diperbolehkan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtBahanPermakKeyTyped

    private void alignTextJSpinnerLeft(){
        JComponent editor = spJmlPermak.getEditor();
        if (editor instanceof JSpinner.DefaultEditor) {
            JSpinner.DefaultEditor defaultEditor = (JSpinner.DefaultEditor) editor;
            JTextField textField = defaultEditor.getTextField();
            textField.setHorizontalAlignment(SwingConstants.LEFT);
        }
    }
    
    public void clear(){
        cbJenisBusanaPermak.setSelectedItem(this);
        txtBahanPermak.setText(null);
        spJmlPermak.setValue(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalPermak;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JComboBox<String> cbJenisBusanaPermak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBahanPermak;
    private javax.swing.JLabel lblJenisBusanaPermak;
    private javax.swing.JLabel lblJmlPermak;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JSpinner spJmlPermak;
    private javax.swing.JTextField txtBahanPermak;
    // End of variables declaration//GEN-END:variables

}
