/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lcbusana;

import database.DataPesanBusana;
import decorationcomponent.RoundedButton;
import decorationcomponent.RoundedPanel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JFrame;
import java.awt.event.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FormPesanBusana_WaktuBiaya extends javax.swing.JPanel {
    private Layout main;
    
    /**
     * Creates new form wbBusana
     * @param frame
     */
    public FormPesanBusana_WaktuBiaya(JFrame frame) {
        initComponents();
        this.main = (Layout) frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        metodePembayaran = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlForm = new RoundedPanel(50);
        lbltgl = new javax.swing.JLabel();
        lblbiaya = new javax.swing.JLabel();
        lblmetode = new javax.swing.JLabel();
        txtbiaya = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        rbtntf = new javax.swing.JRadioButton();
        rbtntunai = new javax.swing.JRadioButton();
        rbtnDP = new javax.swing.JRadioButton();
        jsTanggal = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        btnsblm = new RoundedButton(10);
        btnberikut = new RoundedButton(10);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        jLabel1.setText("Pesan Busana (Waktu dan Biaya)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        pnlForm.setBackground(new java.awt.Color(207, 183, 146));
        pnlForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        pnlForm.setLayout(new java.awt.GridBagLayout());

        lbltgl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltgl.setText("Tanggal Pengambilan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lbltgl, gridBagConstraints);

        lblbiaya.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblbiaya.setText("Biaya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblbiaya, gridBagConstraints);

        lblmetode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblmetode.setText("Metode Pembayaran");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(lblmetode, gridBagConstraints);

        txtbiaya.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtbiaya.setEnabled(false);
        txtbiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbiayaActionPerformed(evt);
            }
        });
        txtbiaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbiayaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(txtbiaya, gridBagConstraints);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        rbtntf.setBackground(new java.awt.Color(207, 183, 146));
        metodePembayaran.add(rbtntf);
        rbtntf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtntf.setText("Transfer");
        rbtntf.setFocusPainted(false);
        rbtntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtntfActionPerformed(evt);
            }
        });
        jPanel5.add(rbtntf);

        rbtntunai.setBackground(new java.awt.Color(207, 183, 146));
        metodePembayaran.add(rbtntunai);
        rbtntunai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtntunai.setText("Tunai");
        rbtntunai.setFocusPainted(false);
        jPanel5.add(rbtntunai);

        rbtnDP.setBackground(new java.awt.Color(207, 183, 146));
        metodePembayaran.add(rbtnDP);
        rbtnDP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtnDP.setText("DP");
        rbtnDP.setFocusPainted(false);
        jPanel5.add(rbtnDP);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jPanel5, gridBagConstraints);

        jsTanggal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jsTanggal.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        jsTanggal.setEditor(new javax.swing.JSpinner.DateEditor(jsTanggal, "d/M/yyyy"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlForm.add(jsTanggal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        jPanel2.add(pnlForm, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnsblm.setBackground(new java.awt.Color(207, 183, 146));
        btnsblm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsblm.setText("< Sebelumnya");
        btnsblm.setBorderPainted(false);
        btnsblm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsblmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(btnsblm, gridBagConstraints);

        btnberikut.setBackground(new java.awt.Color(207, 183, 146));
        btnberikut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnberikut.setText("Berikutnya >");
        btnberikut.setBorderPainted(false);
        btnberikut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnberikutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 80);
        jPanel3.add(btnberikut, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/bg-form.png"));
        Image img = icon.getImage();
        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
    }
    
    private void tampilkanBiaya(){
        DataPesanBusana data = DataPesanBusana.getInstance();
        String biaya = String.valueOf((long) data.getKisaranBudget());
        txtbiaya.setText(biaya);
    }
    
    private void btnberikutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnberikutActionPerformed
        // Ambil nilai dari setiap input field
        Date tanggal = (Date) jsTanggal.getValue();
        long biaya = Long.parseLong(txtbiaya.getText().trim());
        String metode = "";
        
        if (rbtntf.isSelected()) {
            metode = "Transfer";
        } else if (rbtntunai.isSelected()){
            metode = "Tunai";
        } else if (rbtnDP.isSelected()){
            metode = "DP";
        }
        
        //Perbandingan tanggal yang dipilih dengan sekarang
        LocalDate tanggalDipilih = tanggal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate hariIni = LocalDate.now();
        
        // Validasi apakah ada yang kosong
        if (tanggalDipilih.equals(hariIni) || tanggalDipilih.isBefore(hariIni) || biaya <= 0 || metode.equals("")) {
            JOptionPane.showMessageDialog(this, "Semua input harus diisi sebelum melanjutkan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        } 
        
        // Simpan data
        DataPesanBusana data = DataPesanBusana.getInstance();
        data.setTanggalPemakaian(tanggal);
        data.setKisaranBudget(biaya);
        data.setMetodePembayaran(metode);
        
        // Pindah ke halaman selanjutnya Form data diri
        main.ubahPanel("datadiri");
    }//GEN-LAST:event_btnberikutActionPerformed

    private void btnsblmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsblmActionPerformed
        main.ubahPanel("btambahan");
    }//GEN-LAST:event_btnsblmActionPerformed

    private void rbtntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtntfActionPerformed

    private void txtbiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbiayaActionPerformed

    private void txtbiayaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbiayaKeyTyped
        char c = evt.getKeyChar();
    
        // Jika tombol yang ditekan adalah Backspace, biarkan tanpa validasi
        if (c == KeyEvent.VK_BACK_SPACE) {
            return;
        }

        // Blokir angka, tetapi izinkan huruf dan spasi
        if (!Character.isDigit(c)) {
            evt.consume(); // Mencegah angka masuk
            JOptionPane.showMessageDialog(this, "Teks hanya berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtbiayaKeyTyped

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        tampilkanBiaya();
    }//GEN-LAST:event_formComponentShown

    public void clear(){
        jsTanggal.setValue(new Date());
        txtbiaya.setText(null);
        metodePembayaran.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnberikut;
    private javax.swing.JButton btnsblm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jsTanggal;
    private javax.swing.JLabel lblbiaya;
    private javax.swing.JLabel lblmetode;
    private javax.swing.JLabel lbltgl;
    private javax.swing.ButtonGroup metodePembayaran;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JRadioButton rbtnDP;
    private javax.swing.JRadioButton rbtntf;
    private javax.swing.JRadioButton rbtntunai;
    private javax.swing.JTextField txtbiaya;
    // End of variables declaration//GEN-END:variables
}
