/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lcbusana;

import decorationcomponent.RoundedImageButton;
import java.awt.CardLayout;
import lcbusana.auth.FormAuth;
import session.Auth;

/**
 *
 * @author Acer
 */
public class Layout extends javax.swing.JFrame {
    private CardLayout card;
    private String status; //Permak or Busana
    private boolean onEdit = false;
    private FormPesanBusana_Main bmain = new FormPesanBusana_Main(this);
    private FormPesanBusana_Ukuran bukuran = new FormPesanBusana_Ukuran(this);
    private FormPesanBusana_Tambahan btambahan = new FormPesanBusana_Tambahan(this);
    private FormPesanBusana_WaktuBiaya bwaktubiaya = new FormPesanBusana_WaktuBiaya(this);
    private FormPermak_Main pmain = new FormPermak_Main(this);
    private FormPermak_Jenis pjenis = new FormPermak_Jenis(this);
    private FormPermak_Tambahan ptambahan = new FormPermak_Tambahan(this);
    private FormPermak_WaktuBiaya pwaktubiaya = new FormPermak_WaktuBiaya(this);
    private FormDataDiri datadiri = new FormDataDiri(this);      
            
    /**
     * Creates new form Layout
     */
    public Layout() {      
        initComponents();                     
        this.card = (CardLayout) pnlBody.getLayout();
        
        setExtendedState(6);
        komponenBody();
        sesuaikanTampilanAutentikasi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        popUpProfileBAuth = new javax.swing.JPopupMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuRegister = new javax.swing.JMenuItem();
        popUPProfileAAuth = new javax.swing.JPopupMenu();
        menuProfil = new javax.swing.JMenuItem();
        menuLogOut = new javax.swing.JMenuItem();
        pnlNavigasi = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnPesanan = new javax.swing.JButton();
        btnProduk = new javax.swing.JButton();
        btnProfile = new RoundedImageButton();
        pnlBody = new javax.swing.JPanel();

        menuLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuLogin.setText("Log In");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        popUpProfileBAuth.add(menuLogin);

        menuRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuRegister.setText("Register");
        menuRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegisterActionPerformed(evt);
            }
        });
        popUpProfileBAuth.add(menuRegister);

        menuProfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuProfil.setText("Profil");
        popUPProfileAAuth.add(menuProfil);

        menuLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuLogOut.setText("Log Out");
        menuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogOutActionPerformed(evt);
            }
        });
        popUPProfileAAuth.add(menuLogOut);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LC Busana");
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(1100, 650));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlNavigasi.setBackground(new java.awt.Color(207, 183, 146));
        pnlNavigasi.setLayout(new java.awt.GridBagLayout());

        btnHome.setBackground(new java.awt.Color(207, 183, 146));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setFocusPainted(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlNavigasi.add(btnHome, gridBagConstraints);

        btnPesanan.setBackground(new java.awt.Color(207, 183, 146));
        btnPesanan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPesanan.setForeground(new java.awt.Color(0, 0, 0));
        btnPesanan.setText("Pesanan");
        btnPesanan.setBorder(null);
        btnPesanan.setBorderPainted(false);
        btnPesanan.setContentAreaFilled(false);
        btnPesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesanan.setFocusPainted(false);
        btnPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesananActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlNavigasi.add(btnPesanan, gridBagConstraints);

        btnProduk.setBackground(new java.awt.Color(207, 183, 146));
        btnProduk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProduk.setForeground(new java.awt.Color(0, 0, 0));
        btnProduk.setText("Produk");
        btnProduk.setBorder(null);
        btnProduk.setBorderPainted(false);
        btnProduk.setContentAreaFilled(false);
        btnProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduk.setFocusPainted(false);
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 30);
        pnlNavigasi.add(btnProduk, gridBagConstraints);

        btnProfile.setBackground(new java.awt.Color(207, 183, 146));
        btnProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(0, 0, 0));
        btnProfile.setBorder(null);
        btnProfile.setBorderPainted(false);
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.setFocusPainted(false);
        btnProfile.setMinimumSize(new java.awt.Dimension(40, 40));
        btnProfile.setPreferredSize(new java.awt.Dimension(60, 60));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 30);
        pnlNavigasi.add(btnProfile, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(pnlNavigasi, gridBagConstraints);

        pnlBody.setBackground(new java.awt.Color(153, 153, 153));
        pnlBody.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        getContentPane().add(pnlBody, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setStatus(String status){
        this.status = status;
    }
    
    public String getStatus(){
        return this.status;
    }
    
    public CardLayout getLayoutPanel(){
        return this.card;
    }
    
    /**
     * @return the onEdit
     */
    public boolean isOnEdit() {
        return onEdit;
    }

    /**
     * @param onEdit the onEdit to set
     */
    public void setOnEdit(boolean onEdit) {
        this.onEdit = onEdit;
    }
    
    private void btnPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesananActionPerformed
        ubahPanel("pesanan");
    }//GEN-LAST:event_btnPesananActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        ubahPanel("dashboard");      
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        //Menampilkan Pop Up menu, berbeda sebelum dan sesudah terautentikasi
        int offsetX = -btnProfile.getWidth() / 2;
        if(Auth.getInstance().isAuth()){
            popUPProfileAAuth.show(btnProfile, offsetX, btnProfile.getHeight());
        } else {
            popUpProfileBAuth.show(btnProfile, offsetX, btnProfile.getHeight());
        }
    }//GEN-LAST:event_btnProfileActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        //Mengubah ke halaman Login
        dispose();
        FormAuth fAuth = new FormAuth();
        fAuth.setVisible(true);
        fAuth.ubahPanel("Login");
    }//GEN-LAST:event_menuLoginActionPerformed

    private void menuRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegisterActionPerformed
        //Mengubah ke halaman Register
        dispose();
        FormAuth fAuth = new FormAuth();
        fAuth.setVisible(true);
        fAuth.ubahPanel("Register");
    }//GEN-LAST:event_menuRegisterActionPerformed

    private void menuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogOutActionPerformed
        //Kembali ke halaman Autentikasi
        dispose();
        FormAuth fAuth = new FormAuth();
        fAuth.setVisible(true);
    }//GEN-LAST:event_menuLogOutActionPerformed
    
    private void komponenBody(){    
        pnlBody.add(new Dashboard(this), "dashboard");
        pnlBody.add(new Pesanan(this), "pesanan");
        pnlBody.add(bmain, "bmain");
        pnlBody.add(bukuran, "bukuran");
        pnlBody.add(btambahan, "btambahan");
        pnlBody.add(bwaktubiaya, "bwaktubiaya");
        pnlBody.add(pmain, "pmain");
        pnlBody.add(pjenis, "pjenis");
        pnlBody.add(ptambahan, "ptambahan");
        pnlBody.add(pwaktubiaya, "pwaktubiaya");
        pnlBody.add(datadiri, "datadiri");
    }
        
    public void ubahPanel(String namaPanel){
        card.show(pnlBody, namaPanel);
    }
    
    public void pesanBusanaClear(){
        bmain.clear();
        bukuran.clear();
        btambahan.clear();
        bwaktubiaya.clear();
        datadiri.clear();
    }
          
    public void permakBusanaClear(){
        pmain.clear();
        pjenis.clear();
        ptambahan.clear();
        pwaktubiaya.clear();
        datadiri.clear();
    }
    
    public void editPesananBusana(){
        setStatus("Busana");
        setOnEdit(true);
        bmain.isiDataEdit();
        bukuran.isiDataEdit();
        btambahan.isiDataEdit();
        bwaktubiaya.isiDataEdit();   
        
        ubahPanel("bmain");
    }
    
    public void editPesananPermak() {
        setStatus("Permak");
        setOnEdit(true);
        pmain.isiDataEdit();
        pjenis.isiDataEdit();
        ptambahan.isiDataEdit();
        pwaktubiaya.isiDataEdit();
        datadiri.isiDataEditPermakBusana();      
        
        ubahPanel("pmain");
    }
    
    public void keAutentikasi(){
        dispose();
        new FormAuth().setVisible(true);
    }
    
    private void sesuaikanTampilanAutentikasi(){
        if(!Auth.getInstance().isAuth()){
            btnPesanan.setVisible(false);
        } else {
            btnPesanan.setVisible(true);
        }
        
        //Refresh tampilan
        revalidate();
        repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layout().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPesanan;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnProfile;
    private javax.swing.JMenuItem menuLogOut;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuProfil;
    private javax.swing.JMenuItem menuRegister;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlNavigasi;
    private javax.swing.JPopupMenu popUPProfileAAuth;
    private javax.swing.JPopupMenu popUpProfileBAuth;
    // End of variables declaration//GEN-END:variables
}
