/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lcbusana;

import decorationcomponent.RoundedButton;
import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class Pesanan extends javax.swing.JPanel {
    private final Pesanan_Busana pesananBusana = new Pesanan_Busana();
    private CardLayout card;
    private Pesanan_Permak pesananPermak;
    private Layout main;
    
    /**
     * Creates new form Pesanan
     */
    public Pesanan(JFrame frame) {
        initComponents();
        this.card = (CardLayout) pnlDaftarPesanan.getLayout();
        this.main = (Layout) frame;
        this.pesananPermak = new Pesanan_Permak(main);
        
        komponenDaftarPesanan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTombol = new javax.swing.JPanel();
        btnPesananBusana = new RoundedButton(10);
        btnPesananPermak = new RoundedButton(10);
        pnlDaftarPesanan = new javax.swing.JPanel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        pnlTombol.setBackground(new java.awt.Color(255, 255, 255));
        pnlTombol.setLayout(new java.awt.GridBagLayout());

        btnPesananBusana.setBackground(new java.awt.Color(207, 183, 146));
        btnPesananBusana.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesananBusana.setText("Pesanan Busana");
        btnPesananBusana.setBorderPainted(false);
        btnPesananBusana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesananBusanaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 10);
        pnlTombol.add(btnPesananBusana, gridBagConstraints);

        btnPesananPermak.setBackground(new java.awt.Color(207, 183, 146));
        btnPesananPermak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesananPermak.setText("Pesanan Permak");
        btnPesananPermak.setBorderPainted(false);
        btnPesananPermak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesananPermakActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlTombol.add(btnPesananPermak, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        add(pnlTombol, gridBagConstraints);

        pnlDaftarPesanan.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        add(pnlDaftarPesanan, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
  
    private void komponenDaftarPesanan(){    
        pnlDaftarPesanan.add(pesananBusana, "busana");
        pnlDaftarPesanan.add(pesananPermak, "permak");
    }
        
    private void ubahPanel(String namaPanel){
        card.show(pnlDaftarPesanan, namaPanel);
    }
    
    private void btnPesananPermakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesananPermakActionPerformed
        ubahPanel("permak");
    }//GEN-LAST:event_btnPesananPermakActionPerformed

    private void btnPesananBusanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesananBusanaActionPerformed
        ubahPanel("busana");
    }//GEN-LAST:event_btnPesananBusanaActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        pesananBusana.tampilkanDataPesan();
        pesananPermak.tampilkanDataPermak();
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesananBusana;
    private javax.swing.JButton btnPesananPermak;
    private javax.swing.JPanel pnlDaftarPesanan;
    private javax.swing.JPanel pnlTombol;
    // End of variables declaration//GEN-END:variables
}
