/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lcbusana;

import database.DataPesanBusana;
import database.koneksi;
import tools.FormatData;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.JTableHeader;
import tools.ImageUtil;

/**
 *
 * @author Acer
 */
public class Pesanan_Busana extends javax.swing.JPanel {

    /**
     * Creates new form Pesanan_Busana
     */
    public Pesanan_Busana() {
        initComponents();
        
        resizeColumnWidth(tblData);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlStruk = new javax.swing.JPanel();
        scrollStruk = new javax.swing.JScrollPane();
        pnlDataStruk = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbAlamatButik = new javax.swing.JLabel();
        pnlPemisah11 = new javax.swing.JPanel();
        pnlPemisah12 = new javax.swing.JPanel();
        pnlDataPelanggan = new javax.swing.JPanel();
        lbNama = new javax.swing.JLabel();
        lbNoWA = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        lbNilaiNama = new javax.swing.JLabel();
        lbNilaiNoWA = new javax.swing.JLabel();
        lbNilaiEmail = new javax.swing.JLabel();
        lbNilaiAlamat = new javax.swing.JLabel();
        pnlPemisah21 = new javax.swing.JPanel();
        pnlPemisah22 = new javax.swing.JPanel();
        pnlDetailUtama = new javax.swing.JPanel();
        lbJenis = new javax.swing.JLabel();
        lbWarna = new javax.swing.JLabel();
        lbBahan = new javax.swing.JLabel();
        lbModel = new javax.swing.JLabel();
        lbNilaiJenis = new javax.swing.JLabel();
        lbNilaiWarna = new javax.swing.JLabel();
        lbNilaiBahan = new javax.swing.JLabel();
        lbNilaiModel = new javax.swing.JLabel();
        pnlPemisah31 = new javax.swing.JPanel();
        pnlPemisah32 = new javax.swing.JPanel();
        pnlUkuran = new javax.swing.JPanel();
        lbLingkarDada = new javax.swing.JLabel();
        lbLingkarPinggang = new javax.swing.JLabel();
        lbLingkarPinggul = new javax.swing.JLabel();
        lbPanjangLengan = new javax.swing.JLabel();
        lbPanjangBaju = new javax.swing.JLabel();
        lbTinggiBadan = new javax.swing.JLabel();
        lbLebarBahu = new javax.swing.JLabel();
        lbNilaiLingkarDada = new javax.swing.JLabel();
        lbNilaiLingkarPinggang = new javax.swing.JLabel();
        lbNilaiLingkarPinggul = new javax.swing.JLabel();
        lbNilaiPanjangLengan = new javax.swing.JLabel();
        lbNilaiPanjangBaju = new javax.swing.JLabel();
        lbNilaiTinggiBadan = new javax.swing.JLabel();
        lbNilaiLebarBahu = new javax.swing.JLabel();
        pnlPemisah41 = new javax.swing.JPanel();
        pnlPemisah42 = new javax.swing.JPanel();
        pnlDetailTambahan = new javax.swing.JPanel();
        lbAplikasiTambahan = new javax.swing.JLabel();
        lbDetailKhusus = new javax.swing.JLabel();
        lbKebutuhanKhusus = new javax.swing.JLabel();
        lbNilaiAplikasiTambahan = new javax.swing.JLabel();
        lbNilaiDetailKhusus = new javax.swing.JLabel();
        lbNilaiKebutuhanKhusus = new javax.swing.JLabel();
        pnlPemisah51 = new javax.swing.JPanel();
        pnlPemisah52 = new javax.swing.JPanel();
        pnlWaktuBiaya = new javax.swing.JPanel();
        lbTanggal = new javax.swing.JLabel();
        lbBiaya = new javax.swing.JLabel();
        lbMetode = new javax.swing.JLabel();
        lbNilaiTanggal = new javax.swing.JLabel();
        lbNilaiBiaya = new javax.swing.JLabel();
        lbNilaiMetode = new javax.swing.JLabel();
        pnlTable = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0));

        pnlStruk.setOpaque(false);
        pnlStruk.setLayout(new java.awt.GridBagLayout());

        scrollStruk.setToolTipText("");
        scrollStruk.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scrollStruk.setViewportView(pnlDataStruk);

        pnlDataStruk.setBackground(new java.awt.Color(207, 183, 146));
        pnlDataStruk.setLayout(new java.awt.GridBagLayout());

        pnlHeader.setOpaque(false);
        pnlHeader.setLayout(new java.awt.GridBagLayout());

        lbTitle.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        lbTitle.setText("LC Busana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlHeader.add(lbTitle, gridBagConstraints);

        lbAlamatButik.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lbAlamatButik.setText("Jl. Mayorzen, Lr. Harapan Jaya 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlHeader.add(lbAlamatButik, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlHeader, gridBagConstraints);

        pnlPemisah11.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah11.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah11.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah11Layout = new javax.swing.GroupLayout(pnlPemisah11);
        pnlPemisah11.setLayout(pnlPemisah11Layout);
        pnlPemisah11Layout.setHorizontalGroup(
            pnlPemisah11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        pnlPemisah11Layout.setVerticalGroup(
            pnlPemisah11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah11, gridBagConstraints);

        pnlPemisah12.setBackground(new java.awt.Color(0, 0, 0));
        pnlPemisah12.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah12.setOpaque(false);
        pnlPemisah12.setPreferredSize(new java.awt.Dimension(0, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah12, gridBagConstraints);

        pnlDataPelanggan.setOpaque(false);
        pnlDataPelanggan.setLayout(new java.awt.GridBagLayout());

        lbNama.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbNama.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDataPelanggan.add(lbNama, gridBagConstraints);

        lbNoWA.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbNoWA.setText("No Whatsapp              ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDataPelanggan.add(lbNoWA, gridBagConstraints);

        lbEmail.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbEmail.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDataPelanggan.add(lbEmail, gridBagConstraints);

        lbAlamat.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbAlamat.setText("Alamat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDataPelanggan.add(lbAlamat, gridBagConstraints);

        lbNilaiNama.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiNama.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDataPelanggan.add(lbNilaiNama, gridBagConstraints);

        lbNilaiNoWA.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiNoWA.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDataPelanggan.add(lbNilaiNoWA, gridBagConstraints);

        lbNilaiEmail.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiEmail.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDataPelanggan.add(lbNilaiEmail, gridBagConstraints);

        lbNilaiAlamat.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiAlamat.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDataPelanggan.add(lbNilaiAlamat, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlDataPelanggan, gridBagConstraints);

        pnlPemisah21.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah21.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah21.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah21Layout = new javax.swing.GroupLayout(pnlPemisah21);
        pnlPemisah21.setLayout(pnlPemisah21Layout);
        pnlPemisah21Layout.setHorizontalGroup(
            pnlPemisah21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        pnlPemisah21Layout.setVerticalGroup(
            pnlPemisah21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah21, gridBagConstraints);

        pnlPemisah22.setBackground(new java.awt.Color(0, 0, 0));
        pnlPemisah22.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah22.setOpaque(false);
        pnlPemisah22.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah22Layout = new javax.swing.GroupLayout(pnlPemisah22);
        pnlPemisah22.setLayout(pnlPemisah22Layout);
        pnlPemisah22Layout.setHorizontalGroup(
            pnlPemisah22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        pnlPemisah22Layout.setVerticalGroup(
            pnlPemisah22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah22, gridBagConstraints);

        pnlDetailUtama.setOpaque(false);
        pnlDetailUtama.setLayout(new java.awt.GridBagLayout());

        lbJenis.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbJenis.setText("Jenis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailUtama.add(lbJenis, gridBagConstraints);

        lbWarna.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbWarna.setText("Warna                           ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailUtama.add(lbWarna, gridBagConstraints);

        lbBahan.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbBahan.setText("Bahan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailUtama.add(lbBahan, gridBagConstraints);

        lbModel.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbModel.setText("Model");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailUtama.add(lbModel, gridBagConstraints);

        lbNilaiJenis.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiJenis.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailUtama.add(lbNilaiJenis, gridBagConstraints);

        lbNilaiWarna.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiWarna.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailUtama.add(lbNilaiWarna, gridBagConstraints);

        lbNilaiBahan.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiBahan.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailUtama.add(lbNilaiBahan, gridBagConstraints);

        lbNilaiModel.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiModel.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailUtama.add(lbNilaiModel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlDetailUtama, gridBagConstraints);

        pnlPemisah31.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah31.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah31.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah31Layout = new javax.swing.GroupLayout(pnlPemisah31);
        pnlPemisah31.setLayout(pnlPemisah31Layout);
        pnlPemisah31Layout.setHorizontalGroup(
            pnlPemisah31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPemisah31Layout.setVerticalGroup(
            pnlPemisah31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah31, gridBagConstraints);

        pnlPemisah32.setBackground(new java.awt.Color(0, 0, 0));
        pnlPemisah32.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah32.setOpaque(false);
        pnlPemisah32.setPreferredSize(new java.awt.Dimension(0, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah32, gridBagConstraints);

        pnlUkuran.setOpaque(false);
        pnlUkuran.setLayout(new java.awt.GridBagLayout());

        lbLingkarDada.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbLingkarDada.setText("Lingkar Dada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlUkuran.add(lbLingkarDada, gridBagConstraints);

        lbLingkarPinggang.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbLingkarPinggang.setText("Lingkar Pinggang       ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlUkuran.add(lbLingkarPinggang, gridBagConstraints);

        lbLingkarPinggul.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbLingkarPinggul.setText("Lingkar Pinggul");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlUkuran.add(lbLingkarPinggul, gridBagConstraints);

        lbPanjangLengan.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbPanjangLengan.setText("Panjang Lengan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlUkuran.add(lbPanjangLengan, gridBagConstraints);

        lbPanjangBaju.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbPanjangBaju.setText("Panjang Baju");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlUkuran.add(lbPanjangBaju, gridBagConstraints);

        lbTinggiBadan.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbTinggiBadan.setText("Tinggi Badan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlUkuran.add(lbTinggiBadan, gridBagConstraints);

        lbLebarBahu.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbLebarBahu.setText("Lebar Bahu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlUkuran.add(lbLebarBahu, gridBagConstraints);

        lbNilaiLingkarDada.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiLingkarDada.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlUkuran.add(lbNilaiLingkarDada, gridBagConstraints);

        lbNilaiLingkarPinggang.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiLingkarPinggang.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlUkuran.add(lbNilaiLingkarPinggang, gridBagConstraints);

        lbNilaiLingkarPinggul.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiLingkarPinggul.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlUkuran.add(lbNilaiLingkarPinggul, gridBagConstraints);

        lbNilaiPanjangLengan.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiPanjangLengan.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlUkuran.add(lbNilaiPanjangLengan, gridBagConstraints);

        lbNilaiPanjangBaju.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiPanjangBaju.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlUkuran.add(lbNilaiPanjangBaju, gridBagConstraints);

        lbNilaiTinggiBadan.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiTinggiBadan.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlUkuran.add(lbNilaiTinggiBadan, gridBagConstraints);

        lbNilaiLebarBahu.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiLebarBahu.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlUkuran.add(lbNilaiLebarBahu, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlUkuran, gridBagConstraints);

        pnlPemisah41.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah41.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah41.setOpaque(false);
        pnlPemisah41.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah41Layout = new javax.swing.GroupLayout(pnlPemisah41);
        pnlPemisah41.setLayout(pnlPemisah41Layout);
        pnlPemisah41Layout.setHorizontalGroup(
            pnlPemisah41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        pnlPemisah41Layout.setVerticalGroup(
            pnlPemisah41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah41, gridBagConstraints);

        pnlPemisah42.setBackground(new java.awt.Color(0, 0, 0));
        pnlPemisah42.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah42.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah42Layout = new javax.swing.GroupLayout(pnlPemisah42);
        pnlPemisah42.setLayout(pnlPemisah42Layout);
        pnlPemisah42Layout.setHorizontalGroup(
            pnlPemisah42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        pnlPemisah42Layout.setVerticalGroup(
            pnlPemisah42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah42, gridBagConstraints);

        pnlDetailTambahan.setOpaque(false);
        pnlDetailTambahan.setLayout(new java.awt.GridBagLayout());

        lbAplikasiTambahan.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbAplikasiTambahan.setText("Aplikasi Tambahan    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailTambahan.add(lbAplikasiTambahan, gridBagConstraints);

        lbDetailKhusus.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbDetailKhusus.setText("Detail Khusus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailTambahan.add(lbDetailKhusus, gridBagConstraints);

        lbKebutuhanKhusus.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbKebutuhanKhusus.setText("Kebutuhan Khusus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailTambahan.add(lbKebutuhanKhusus, gridBagConstraints);

        lbNilaiAplikasiTambahan.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiAplikasiTambahan.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailTambahan.add(lbNilaiAplikasiTambahan, gridBagConstraints);

        lbNilaiDetailKhusus.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiDetailKhusus.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailTambahan.add(lbNilaiDetailKhusus, gridBagConstraints);

        lbNilaiKebutuhanKhusus.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiKebutuhanKhusus.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailTambahan.add(lbNilaiKebutuhanKhusus, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlDetailTambahan, gridBagConstraints);

        pnlPemisah51.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah51.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah51.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah51Layout = new javax.swing.GroupLayout(pnlPemisah51);
        pnlPemisah51.setLayout(pnlPemisah51Layout);
        pnlPemisah51Layout.setHorizontalGroup(
            pnlPemisah51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPemisah51Layout.setVerticalGroup(
            pnlPemisah51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah51, gridBagConstraints);

        pnlPemisah52.setBackground(new java.awt.Color(0, 0, 0));
        pnlPemisah52.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah52.setOpaque(false);
        pnlPemisah52.setPreferredSize(new java.awt.Dimension(0, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah52, gridBagConstraints);

        pnlWaktuBiaya.setOpaque(false);
        pnlWaktuBiaya.setLayout(new java.awt.GridBagLayout());

        lbTanggal.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbTanggal.setText("Tanggal Pengambilan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlWaktuBiaya.add(lbTanggal, gridBagConstraints);

        lbBiaya.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbBiaya.setText("Biaya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlWaktuBiaya.add(lbBiaya, gridBagConstraints);

        lbMetode.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbMetode.setText("Metode Pembayaran");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlWaktuBiaya.add(lbMetode, gridBagConstraints);

        lbNilaiTanggal.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiTanggal.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlWaktuBiaya.add(lbNilaiTanggal, gridBagConstraints);

        lbNilaiBiaya.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiBiaya.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlWaktuBiaya.add(lbNilaiBiaya, gridBagConstraints);

        lbNilaiMetode.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiMetode.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlWaktuBiaya.add(lbNilaiMetode, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlWaktuBiaya, gridBagConstraints);

        scrollStruk.setViewportView(pnlDataStruk);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 10);
        pnlStruk.add(scrollStruk, gridBagConstraints);

        add(pnlStruk);

        pnlTable.setOpaque(false);
        pnlTable.setLayout(new java.awt.GridBagLayout());

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Lengkap", "Nomor Telepon", "Alamat Email", "Alamat Pengiriman", "Jenis Busana", "Model Desain", "Warna", "Bahan", "Lingkar  Dada", "Lingkar Pinggang", "Lingkar Pinggul", "Panjang Lengan", "Panjang Baju", "Tinggi Badan", "Lebar Bahu", "Apikasi Tambahan", "Detail Khusus", "Kebutuhan Khusus", "Tanggal Pemakaian", "Kisaran Budget", "Metode Pembayaran"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        scrollTable.setViewportView(tblData);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 20);
        pnlTable.add(scrollTable, gridBagConstraints);

        add(pnlTable);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        tampilkanDataPesan();
    }//GEN-LAST:event_formComponentShown

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int selectedRow = tblData.getSelectedRow(); // Ambil baris yang diklik
        
        if (selectedRow != -1) { // Pastikan ada baris yang dipilih
            //Mengambil seluruh nilai dalam satu baris yang dipilih
            List<String> row = new ArrayList();
            for (int i = 0; i < tblData.getColumnCount(); i++) {
                row.add(tblData.getValueAt(selectedRow, i).toString()); // Tambahkan data ke list
            }
            
            //Memperbarui Nilai Struk
            lbNilaiNama.setText(row.get(0));
            lbNilaiNoWA.setText(row.get(1));
            lbNilaiEmail.setText(row.get(2));
            lbNilaiAlamat.setText(row.get(3));
            lbNilaiJenis.setText(row.get(4));
            lbNilaiBahan.setText(row.get(7));
            lbNilaiLingkarDada.setText(FormatData.toCm(row.get(8)));
            lbNilaiLingkarPinggang.setText(FormatData.toCm(row.get(9)));
            lbNilaiLingkarPinggul.setText(FormatData.toCm(row.get(10)));
            lbNilaiPanjangLengan.setText(FormatData.toCm(row.get(11)));
            lbNilaiPanjangBaju.setText(FormatData.toCm(row.get(12)));
            lbNilaiTinggiBadan.setText(FormatData.toCm(row.get(13)));
            lbNilaiLebarBahu.setText(FormatData.toCm(row.get(14)));
            lbNilaiAplikasiTambahan.setText(row.get(15));
            lbNilaiDetailKhusus.setText(row.get(16));
            lbNilaiKebutuhanKhusus.setText(row.get(17));
            lbNilaiTanggal.setText(FormatData.tanggal(row.get(18)));
            
            //Mengatur nilai harga berdasarkan metode
            String biaya = row.get(19);
            String metode = row.get(20);
            lbNilaiBiaya.setText(FormatData.toRupiah(biaya)+cekHargaDP(Double.parseDouble(biaya), metode));
            lbNilaiMetode.setText(metode);
            
            
            //Menampilkan Gambar pada Model 
            ImageUtil.setImageToLabel(lbNilaiModel, row.get(5));
            
            //Mengubah background Warna sesuai warna yang dipilih
            lbNilaiWarna.setText(" ");
            lbNilaiWarna.setBackground(FormatData.rgbStringToColor(row.get(6)));
            lbNilaiWarna.setOpaque(true);
            lbNilaiWarna.repaint();
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        JTableHeader header = table.getTableHeader();

        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 50; // Lebar minimum default

            // Ambil ukuran teks dari header (judul kolom)
            TableCellRenderer headerRenderer = header.getDefaultRenderer();
            Component headerComp = headerRenderer.getTableCellRendererComponent(table, 
                    table.getColumnName(column), false, false, -1, column);
            width = Math.max(headerComp.getPreferredSize().width + 10, width);

            // Ambil ukuran teks dari setiap sel data
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 10, width);
            }

            // Set lebar kolom berdasarkan ukuran terbesar antara header dan isi
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }
    
    public void tampilkanDataPesanByClass(){
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.setRowCount(0); // Menghapus data lama
        List<List<Object>> dataPesan = DataPesanBusana.getInstance().getHistoryData();
    
        for (List<Object> row : dataPesan) {
            model.addRow(row.toArray());
        }
        
        tblData.setModel(model);
    }
    
    public void tampilkanDataPesan(){
        String query = "SELECT * FROM view_pesanan_busana";
        try(Connection conn = koneksi.getConnection();
                PreparedStatement stmt = conn.prepareStatement(query);
                ResultSet rs = stmt.executeQuery()){
            
            DefaultTableModel model = (DefaultTableModel) tblData.getModel();
            model.setRowCount(0); // Menghapus data lama
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            
            while (rs.next()) {
                Object[] rowData = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    rowData[i - 1] = rs.getObject(i);
                }
                model.addRow(rowData);
            }
        } catch(SQLException e){
            System.out.println("Gagal mengambil data: " + e.getMessage()); 
        }
    }
    
    private String cekHargaDP(Double harga, String metode){
        if(metode.equals("DP")){
            return " (DP: " + FormatData.toRupiah(String.valueOf(harga*0.5)) + ")";
        } else {
            return "";  
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbAlamatButik;
    private javax.swing.JLabel lbAplikasiTambahan;
    private javax.swing.JLabel lbBahan;
    private javax.swing.JLabel lbBiaya;
    private javax.swing.JLabel lbDetailKhusus;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbJenis;
    private javax.swing.JLabel lbKebutuhanKhusus;
    private javax.swing.JLabel lbLebarBahu;
    private javax.swing.JLabel lbLingkarDada;
    private javax.swing.JLabel lbLingkarPinggang;
    private javax.swing.JLabel lbLingkarPinggul;
    private javax.swing.JLabel lbMetode;
    private javax.swing.JLabel lbModel;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbNilaiAlamat;
    private javax.swing.JLabel lbNilaiAplikasiTambahan;
    private javax.swing.JLabel lbNilaiBahan;
    private javax.swing.JLabel lbNilaiBiaya;
    private javax.swing.JLabel lbNilaiDetailKhusus;
    private javax.swing.JLabel lbNilaiEmail;
    private javax.swing.JLabel lbNilaiJenis;
    private javax.swing.JLabel lbNilaiKebutuhanKhusus;
    private javax.swing.JLabel lbNilaiLebarBahu;
    private javax.swing.JLabel lbNilaiLingkarDada;
    private javax.swing.JLabel lbNilaiLingkarPinggang;
    private javax.swing.JLabel lbNilaiLingkarPinggul;
    private javax.swing.JLabel lbNilaiMetode;
    private javax.swing.JLabel lbNilaiModel;
    private javax.swing.JLabel lbNilaiNama;
    private javax.swing.JLabel lbNilaiNoWA;
    private javax.swing.JLabel lbNilaiPanjangBaju;
    private javax.swing.JLabel lbNilaiPanjangLengan;
    private javax.swing.JLabel lbNilaiTanggal;
    private javax.swing.JLabel lbNilaiTinggiBadan;
    private javax.swing.JLabel lbNilaiWarna;
    private javax.swing.JLabel lbNoWA;
    private javax.swing.JLabel lbPanjangBaju;
    private javax.swing.JLabel lbPanjangLengan;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JLabel lbTinggiBadan;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbWarna;
    private javax.swing.JPanel pnlDataPelanggan;
    private javax.swing.JPanel pnlDataStruk;
    private javax.swing.JPanel pnlDetailTambahan;
    private javax.swing.JPanel pnlDetailUtama;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPemisah11;
    private javax.swing.JPanel pnlPemisah12;
    private javax.swing.JPanel pnlPemisah21;
    private javax.swing.JPanel pnlPemisah22;
    private javax.swing.JPanel pnlPemisah31;
    private javax.swing.JPanel pnlPemisah32;
    private javax.swing.JPanel pnlPemisah41;
    private javax.swing.JPanel pnlPemisah42;
    private javax.swing.JPanel pnlPemisah51;
    private javax.swing.JPanel pnlPemisah52;
    private javax.swing.JPanel pnlStruk;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlUkuran;
    private javax.swing.JPanel pnlWaktuBiaya;
    private javax.swing.JScrollPane scrollStruk;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
