/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package lcbusana;

import java.util.List;
import session.Auth;
import tools.FormatData;
import tools.ImageUtil;

/**
 *
 * @author Acer
 */
public class Struk_Permak extends javax.swing.JDialog {
    private static List<String> data;
    
    /**
     * Creates new form Struk_Permak
     */
    public Struk_Permak(java.awt.Frame parent, boolean modal, List<String> data) {
        super(parent, modal);
        this.data = data;
                
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollStruk = new javax.swing.JScrollPane();
        pnlDataStruk = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbAlamatButik = new javax.swing.JLabel();
        pnlPemisah11 = new javax.swing.JPanel();
        pnlPemisah12 = new javax.swing.JPanel();
        pnlDataPelanggan = new javax.swing.JPanel();
        lbNama = new javax.swing.JLabel();
        lbNoWA = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        lbNilaiNama = new javax.swing.JLabel();
        lbNilaiNoWA = new javax.swing.JLabel();
        lbNilaiEmail = new javax.swing.JLabel();
        lbNilaiAlamat = new javax.swing.JLabel();
        pnlPemisah21 = new javax.swing.JPanel();
        pnlPemisah22 = new javax.swing.JPanel();
        pnlDetailUtama = new javax.swing.JPanel();
        lbJenis = new javax.swing.JLabel();
        lbBahan = new javax.swing.JLabel();
        lbJumlah = new javax.swing.JLabel();
        lbNilaiJenis = new javax.swing.JLabel();
        lbNilaiBahan = new javax.swing.JLabel();
        lbNilaiJumlah = new javax.swing.JLabel();
        pnlPemisah31 = new javax.swing.JPanel();
        pnlPemisah32 = new javax.swing.JPanel();
        pnlUkuran = new javax.swing.JPanel();
        lbJenisPerbaikan = new javax.swing.JLabel();
        lbUkuran = new javax.swing.JLabel();
        lbNilaiJenisPerbaikan = new javax.swing.JLabel();
        lbNilaiUkuran = new javax.swing.JLabel();
        pnlPemisah41 = new javax.swing.JPanel();
        pnlPemisah42 = new javax.swing.JPanel();
        pnlDetailTambahan = new javax.swing.JPanel();
        lbGambarPakaian = new javax.swing.JLabel();
        lbDeskripsi = new javax.swing.JLabel();
        lbNilaiGambarPakaian = new javax.swing.JLabel();
        lbNilaiDeskripsiTambahan = new javax.swing.JLabel();
        pnlPemisah51 = new javax.swing.JPanel();
        pnlPemisah52 = new javax.swing.JPanel();
        pnlWaktuBiaya = new javax.swing.JPanel();
        lbTanggal = new javax.swing.JLabel();
        lbBiaya = new javax.swing.JLabel();
        lbMetode = new javax.swing.JLabel();
        lbNilaiTanggal = new javax.swing.JLabel();
        lbNilaiBiaya = new javax.swing.JLabel();
        lbNilaiMetode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Struk Permak");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        scrollStruk.setToolTipText("");
        scrollStruk.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlDataStruk.setBackground(new java.awt.Color(207, 183, 146));
        pnlDataStruk.setLayout(new java.awt.GridBagLayout());

        pnlHeader.setOpaque(false);
        pnlHeader.setLayout(new java.awt.GridBagLayout());

        lbTitle.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        lbTitle.setText("LC Busana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlHeader.add(lbTitle, gridBagConstraints);

        lbAlamatButik.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lbAlamatButik.setText("Jl. Mayorzen, Lr. Harapan Jaya 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlHeader.add(lbAlamatButik, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlHeader, gridBagConstraints);

        pnlPemisah11.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah11.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah11.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah11Layout = new javax.swing.GroupLayout(pnlPemisah11);
        pnlPemisah11.setLayout(pnlPemisah11Layout);
        pnlPemisah11Layout.setHorizontalGroup(
            pnlPemisah11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        pnlPemisah11Layout.setVerticalGroup(
            pnlPemisah11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah11, gridBagConstraints);

        pnlPemisah12.setBackground(new java.awt.Color(0, 0, 0));
        pnlPemisah12.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah12.setOpaque(false);
        pnlPemisah12.setPreferredSize(new java.awt.Dimension(0, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah12, gridBagConstraints);

        pnlDataPelanggan.setOpaque(false);
        pnlDataPelanggan.setLayout(new java.awt.GridBagLayout());

        lbNama.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbNama.setText("Nama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDataPelanggan.add(lbNama, gridBagConstraints);

        lbNoWA.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbNoWA.setText("No Whatsapp                        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDataPelanggan.add(lbNoWA, gridBagConstraints);

        lbEmail.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbEmail.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDataPelanggan.add(lbEmail, gridBagConstraints);

        lbAlamat.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbAlamat.setText("Alamat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDataPelanggan.add(lbAlamat, gridBagConstraints);

        lbNilaiNama.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiNama.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDataPelanggan.add(lbNilaiNama, gridBagConstraints);

        lbNilaiNoWA.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiNoWA.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDataPelanggan.add(lbNilaiNoWA, gridBagConstraints);

        lbNilaiEmail.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiEmail.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDataPelanggan.add(lbNilaiEmail, gridBagConstraints);

        lbNilaiAlamat.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiAlamat.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDataPelanggan.add(lbNilaiAlamat, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlDataPelanggan, gridBagConstraints);

        pnlPemisah21.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah21.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah21.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah21Layout = new javax.swing.GroupLayout(pnlPemisah21);
        pnlPemisah21.setLayout(pnlPemisah21Layout);
        pnlPemisah21Layout.setHorizontalGroup(
            pnlPemisah21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        pnlPemisah21Layout.setVerticalGroup(
            pnlPemisah21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah21, gridBagConstraints);

        pnlPemisah22.setBackground(new java.awt.Color(0, 0, 0));
        pnlPemisah22.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah22.setOpaque(false);
        pnlPemisah22.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah22Layout = new javax.swing.GroupLayout(pnlPemisah22);
        pnlPemisah22.setLayout(pnlPemisah22Layout);
        pnlPemisah22Layout.setHorizontalGroup(
            pnlPemisah22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        pnlPemisah22Layout.setVerticalGroup(
            pnlPemisah22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah22, gridBagConstraints);

        pnlDetailUtama.setOpaque(false);
        pnlDetailUtama.setLayout(new java.awt.GridBagLayout());

        lbJenis.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbJenis.setText("Jenis Pakaian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailUtama.add(lbJenis, gridBagConstraints);

        lbBahan.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbBahan.setText("Bahan Pakaian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailUtama.add(lbBahan, gridBagConstraints);

        lbJumlah.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbJumlah.setText("Jumlah Pakaian                    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailUtama.add(lbJumlah, gridBagConstraints);

        lbNilaiJenis.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiJenis.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailUtama.add(lbNilaiJenis, gridBagConstraints);

        lbNilaiBahan.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiBahan.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailUtama.add(lbNilaiBahan, gridBagConstraints);

        lbNilaiJumlah.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiJumlah.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailUtama.add(lbNilaiJumlah, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlDetailUtama, gridBagConstraints);

        pnlPemisah31.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah31.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah31.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah31Layout = new javax.swing.GroupLayout(pnlPemisah31);
        pnlPemisah31.setLayout(pnlPemisah31Layout);
        pnlPemisah31Layout.setHorizontalGroup(
            pnlPemisah31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        pnlPemisah31Layout.setVerticalGroup(
            pnlPemisah31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah31, gridBagConstraints);

        pnlPemisah32.setBackground(new java.awt.Color(0, 0, 0));
        pnlPemisah32.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah32.setOpaque(false);
        pnlPemisah32.setPreferredSize(new java.awt.Dimension(0, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah32, gridBagConstraints);

        pnlUkuran.setOpaque(false);
        pnlUkuran.setLayout(new java.awt.GridBagLayout());

        lbJenisPerbaikan.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbJenisPerbaikan.setText("Jenis Perbaikan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlUkuran.add(lbJenisPerbaikan, gridBagConstraints);

        lbUkuran.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbUkuran.setText("Ukuran Setelah diperbaiki");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlUkuran.add(lbUkuran, gridBagConstraints);

        lbNilaiJenisPerbaikan.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiJenisPerbaikan.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlUkuran.add(lbNilaiJenisPerbaikan, gridBagConstraints);

        lbNilaiUkuran.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiUkuran.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlUkuran.add(lbNilaiUkuran, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlUkuran, gridBagConstraints);

        pnlPemisah41.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah41.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah41.setOpaque(false);
        pnlPemisah41.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah41Layout = new javax.swing.GroupLayout(pnlPemisah41);
        pnlPemisah41.setLayout(pnlPemisah41Layout);
        pnlPemisah41Layout.setHorizontalGroup(
            pnlPemisah41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        pnlPemisah41Layout.setVerticalGroup(
            pnlPemisah41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah41, gridBagConstraints);

        pnlPemisah42.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah42.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah42.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah42Layout = new javax.swing.GroupLayout(pnlPemisah42);
        pnlPemisah42.setLayout(pnlPemisah42Layout);
        pnlPemisah42Layout.setHorizontalGroup(
            pnlPemisah42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        pnlPemisah42Layout.setVerticalGroup(
            pnlPemisah42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah42, gridBagConstraints);

        pnlDetailTambahan.setOpaque(false);
        pnlDetailTambahan.setLayout(new java.awt.GridBagLayout());

        lbGambarPakaian.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbGambarPakaian.setText("Gambar Pakaian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailTambahan.add(lbGambarPakaian, gridBagConstraints);

        lbDeskripsi.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbDeskripsi.setText("Deskripsi Tambahan           ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlDetailTambahan.add(lbDeskripsi, gridBagConstraints);

        lbNilaiGambarPakaian.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiGambarPakaian.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailTambahan.add(lbNilaiGambarPakaian, gridBagConstraints);

        lbNilaiDeskripsiTambahan.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiDeskripsiTambahan.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlDetailTambahan.add(lbNilaiDeskripsiTambahan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlDetailTambahan, gridBagConstraints);

        pnlPemisah51.setBackground(new java.awt.Color(54, 35, 18));
        pnlPemisah51.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah51.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlPemisah51Layout = new javax.swing.GroupLayout(pnlPemisah51);
        pnlPemisah51.setLayout(pnlPemisah51Layout);
        pnlPemisah51Layout.setHorizontalGroup(
            pnlPemisah51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        pnlPemisah51Layout.setVerticalGroup(
            pnlPemisah51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah51, gridBagConstraints);

        pnlPemisah52.setBackground(new java.awt.Color(0, 0, 0));
        pnlPemisah52.setMaximumSize(new java.awt.Dimension(32767, 3));
        pnlPemisah52.setOpaque(false);
        pnlPemisah52.setPreferredSize(new java.awt.Dimension(0, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlPemisah52, gridBagConstraints);

        pnlWaktuBiaya.setOpaque(false);
        pnlWaktuBiaya.setLayout(new java.awt.GridBagLayout());

        lbTanggal.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbTanggal.setText("Tanggal Pengembalian        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlWaktuBiaya.add(lbTanggal, gridBagConstraints);

        lbBiaya.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbBiaya.setText("Biaya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlWaktuBiaya.add(lbBiaya, gridBagConstraints);

        lbMetode.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lbMetode.setText("Metode Pembayaran");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        pnlWaktuBiaya.add(lbMetode, gridBagConstraints);

        lbNilaiTanggal.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiTanggal.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlWaktuBiaya.add(lbNilaiTanggal, gridBagConstraints);

        lbNilaiBiaya.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiBiaya.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlWaktuBiaya.add(lbNilaiBiaya, gridBagConstraints);

        lbNilaiMetode.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbNilaiMetode.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        pnlWaktuBiaya.add(lbNilaiMetode, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlDataStruk.add(pnlWaktuBiaya, gridBagConstraints);

        scrollStruk.setViewportView(pnlDataStruk);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 399;
        gridBagConstraints.ipady = 468;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(scrollStruk, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(){
        //Memperbarui Nilai Struk
        lbNilaiJenis.setText(data.get(0));
        lbNilaiBahan.setText(data.get(1));
        lbNilaiJumlah.setText(data.get(2));
        lbNilaiJenisPerbaikan.setText("<html>" + data.get(3).replace(",", "<br>") + "</html>");
        lbNilaiUkuran.setText(FormatData.toCm(data.get(4)));
        lbNilaiDeskripsiTambahan.setText(data.get(6));
        lbNilaiTanggal.setText(FormatData.sqlDateToTanggal(data.get(7)));

        //Mengatur nilai harga berdasarkan metode
        String biaya = data.get(8);
        String metode = data.get(9);
        lbNilaiBiaya.setText(FormatData.toRupiah(biaya)+cekHargaDP(Double.parseDouble(biaya), metode));
        lbNilaiMetode.setText(metode);

        //Menampilkan Gambar pada Model 
        String imagePath = "attachments/PermakBusana/" + data.get(5).toString();
        ImageUtil.setImageToLabel(lbNilaiGambarPakaian, imagePath);
        
        //Menampilkan data diri di struk
        Auth auth = Auth.getInstance();
        lbNilaiNama.setText(auth.getNamaLengkap());
        lbNilaiNoWA.setText(auth.getNomorWa());
        lbNilaiEmail.setText(auth.getEmail());
        lbNilaiAlamat.setText(auth.getAlamat());
    }
    
    private String cekHargaDP(Double harga, String metode){
        if(metode.equals("DP")){
            return " (DP: " + FormatData.toRupiah(String.valueOf(harga*0.5)) + ")";
        } else {
            return "";  
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Struk_Permak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Struk_Permak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Struk_Permak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Struk_Permak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Struk_Permak dialog = new Struk_Permak(new javax.swing.JFrame(), true, data);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbAlamatButik;
    private javax.swing.JLabel lbBahan;
    private javax.swing.JLabel lbBiaya;
    private javax.swing.JLabel lbDeskripsi;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGambarPakaian;
    private javax.swing.JLabel lbJenis;
    private javax.swing.JLabel lbJenisPerbaikan;
    private javax.swing.JLabel lbJumlah;
    private javax.swing.JLabel lbMetode;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbNilaiAlamat;
    private javax.swing.JLabel lbNilaiBahan;
    private javax.swing.JLabel lbNilaiBiaya;
    private javax.swing.JLabel lbNilaiDeskripsiTambahan;
    private javax.swing.JLabel lbNilaiEmail;
    private javax.swing.JLabel lbNilaiGambarPakaian;
    private javax.swing.JLabel lbNilaiJenis;
    private javax.swing.JLabel lbNilaiJenisPerbaikan;
    private javax.swing.JLabel lbNilaiJumlah;
    private javax.swing.JLabel lbNilaiMetode;
    private javax.swing.JLabel lbNilaiNama;
    private javax.swing.JLabel lbNilaiNoWA;
    private javax.swing.JLabel lbNilaiTanggal;
    private javax.swing.JLabel lbNilaiUkuran;
    private javax.swing.JLabel lbNoWA;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUkuran;
    private javax.swing.JPanel pnlDataPelanggan;
    private javax.swing.JPanel pnlDataStruk;
    private javax.swing.JPanel pnlDetailTambahan;
    private javax.swing.JPanel pnlDetailUtama;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPemisah11;
    private javax.swing.JPanel pnlPemisah12;
    private javax.swing.JPanel pnlPemisah21;
    private javax.swing.JPanel pnlPemisah22;
    private javax.swing.JPanel pnlPemisah31;
    private javax.swing.JPanel pnlPemisah32;
    private javax.swing.JPanel pnlPemisah41;
    private javax.swing.JPanel pnlPemisah42;
    private javax.swing.JPanel pnlPemisah51;
    private javax.swing.JPanel pnlPemisah52;
    private javax.swing.JPanel pnlUkuran;
    private javax.swing.JPanel pnlWaktuBiaya;
    private javax.swing.JScrollPane scrollStruk;
    // End of variables declaration//GEN-END:variables
}
